### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by bsacheri** [Evanml2030/SpaceInvader#1]
I found out about your project on [CodeReview](https://codereview.stackexchange.com/questions/203274/spaceinvaders-second-iteration-fully-functional-next-up-new-presenter-class) but I don't have enough reputation to comment there.
Could you update your `README.md` to explain how to open and run this project?   Does this run in VBA from Excel, Access, wscript.exe, or somewhere else?

**Comment by bsacheri** [comment]
I found the `SpaceInvadersRefactored.xlsm` file so I now know this runs inside Excel.

To start the game, run the `RunGame` sub in the `GameLogic` module.   It would be helpful to have a button on Sheet1 that will call the _RunGame_ sub.

A user needs to update the hard coded paths.  They aren't found in the modules as described in the readme.  I suggest doing a Find for `"C:\Users\evanm\OneDrive\Desktop\Excel\SpaceInvader` and Replace with `ActiveWorkbook.Path & "`  Then it will work for anyone.

A file in this release has a typo.   Rename `Missle.jpg` to `Missile.jpg`

After making those changes I was able to run the game.   After my second game ended, Excel crashed.  Maybe a class didn't release properly.  That's a tough one to find due to the number of classes you're using.

**Comment by Evanml2030** [comment]
Thank you very much. I am revamping this completely. Hopefully this will cut down on the number of classes. It will also, hopefully, completely decouple the game state / logic from the view. I will create my UI using userforms again, but this should allow for the creation of different views, say one inside a worksheet, though trapping keys may be difficult. 

I always stopped the game from running by hitting reset. I have a feeling that hitting the "x button" on the view does not reset the classes.

I will create a button to launch game, update filepath string, change the name to the jpg and update read.me tomorrow night.

Tonight am working on this new way of building it! 

Thank you for taking the time to test / review

**Comment by bsacheri** [comment]
I'm not trying to hassle you but I posted my last comments on [Code Review](https://codereview.stackexchange.com/a/203843/160787).  I'm new there and was hoping that it gives me some reputation on the site so then I can add comments.  

I recommended that you try the free VBA add-in [Smart Indenter](http://www.oaltd.co.uk/indenter/indentpage.asp).  I'm happy with 98% of how it indents and it's great when you inherit someone else's code.  You can right-click and run it on a procedure, module, or entire project.

**Comment by Evanml2030** [comment]
I gave you a +1 thank you again for the additional help.

Are you familiar with [RubberDuck](http://rubberduckvba.com/)

 The have similar functionality. I just haven't had time to explore it yet.

**Comment by bsacheri** [comment]
I've heard of RubberDuck and thought about using it but haven't tried it
yet.  I see that they are using the Smart Indenter algorithm.
